baseURL: https://yintingchou.com/
title: My Blog
author: Yin-Ting Chou
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
footnoteReturnLinkContents: ^
theme: harbor
Author:
  name: Yin-Ting Chou
permalinks:
  page: /:filename/
  post: /posts/:filename/
outputs:
  section:
    - JSON
    - HTML
googleAnalytics: "UA-90830701-1"
params:
  favicon: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: icon.png
    width: 50
  mainSections: post
  math: true
  nav:
    - icon: fas fa-user fa-lg
      identifier: about
      name: About
      url: /about/
      weight: 3
    - icon: fas fa-folder-open fa-lg
      identifier: categories
      name: Category
      url: /categories/
      weight: 3
    - icon: fas fa-archive fa-lg
      identifier: archives
      name: Archives
      url: /archives/
      weight: 3
    - icon: fas fa-search fa-lg
      identifier: search
      name: Search
      url: /search/
      weight: 3
  social:
    - icon: fab fa-github
      name: github
      url: https://github.com/choux130
